name: Recurring checks

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 22 * * *' # daily at 7pm UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  code-checks:
    name: Source code analysis
    runs-on: ubuntu-24.04
    container: quay.io/tnozicka/images:golang-tools-1.26
    timeout-minutes: 15
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags so git describe works.

    - name: Run govulncheck
      run: govulncheck ./...
