name: Go

on:
  push:
    branches:
    - master
    - 'release-[0-9]+.[0-9]+'
  pull_request:
    branches:
    - '**'
    types:
    - opened
    - edited
    - reopened
    - synchronize
  merge_group:
  schedule:
  - cron:  '0 19 * * *' # daily at 7pm UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  id-token: write
  contents: read
  packages: write

env:
  retention_days: 90

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    container:
      image: quay.io/tnozicka/images:golang-tools-1.26
      options: --user 1001:1001
      volumes:
      - /home/runner:/root
    timeout-minutes: 15
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags so git describe works.

    - name: Verify
      run: make verify -k --warn-undefined-variables

  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    container:
      image: quay.io/tnozicka/images:golang-tools-1.26
      options: --user 1001:1001
      volumes:
      - /home/runner:/root
    timeout-minutes: 15
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags so git describe works.

    - name: Build
      run: make build --warn-undefined-variables

  test-unit:
    name: Test unit
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    container:
      image: quay.io/tnozicka/images:golang-tools-1.26
      options: --user 1001:1001
      volumes:
      - /home/runner:/root
    timeout-minutes: 15
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags so git describe works.

    - name: Make sure new unit tests aren't flaky
      if: contains(fromJSON('["pull_request","merge_group"]'), github.event_name)
      run: |
        set -euExo pipefail
        shopt -s inherit_errexit
        
        echo "GO_TEST_EXTRA_FLAGS=-count=3" | tee -a ${GITHUB_ENV}

    - name: Test
      run: make test --warn-undefined-variables

  image-build:
    name: Build images (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    steps:
    - name: Check out code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags so git describe works.

    - name: Log in to CI container image registry
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo "${GITHUB_TOKEN}" | buildah login "ghcr.io/${{ github.repository }}" -u="${GITHUB_ACTOR}" --password-stdin

    - name: Build images
      shell: bash
      run: |
        set -euExo pipefail
        shopt -s inherit_errexit

        image_ref="ghcr.io/${{ github.repository }}:ktool-ci-${{ github.run_number }}-${{ github.run_attempt }}-${{ matrix.arch }}"
        
        git_revision="$( git rev-parse HEAD )"
        buildah build --squash --format=docker \
        --label="org.opencontainers.image.revision=${git_revision}" \
        --tag="${image_ref}" .
        
        digestfile="$( mktemp )"
        buildah push --digestfile="${digestfile}" "${image_ref}"
        echo '' | cat "${digestfile}" -

  image-manifest:
    name: Create manifest list
    runs-on: ubuntu-24.04
    needs:
    - image-build
    timeout-minutes: 30
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Configure promotions
      shell: bash
      if: ${{ contains(fromJSON('["push", "schedule"]'), github.event_name) }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo "CI_PROMOTE=true" | tee -a "${GITHUB_ENV}"

    - name: Log in to CI container image registry
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo "${GITHUB_TOKEN}" | buildah login "ghcr.io/${{ github.repository }}" -u="${GITHUB_ACTOR}" --password-stdin

    - name: Log in to quay
      shell: bash
      if: ${{ env.CI_PROMOTE == 'true' }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo '${{ secrets.QUAY_PASSWORD }}' | buildah login 'quay.io/tnozicka/ktool' -u='${{ secrets.QUAY_USER }}' --password-stdin

    - name: Assemble images
      shell: bash
      run: |
        set -euExo pipefail
        shopt -s inherit_errexit

        ci_repo_ref="ghcr.io/${{ github.repository }}:ktool"
        ci_image_ref="${ci_repo_ref}-ci-${{ github.run_number }}-${{ github.run_attempt }}"

        source ./hack/ci/lib/tag-from-gh-ref.sh
        
        buildah manifest create "${ci_image_ref}"
        for arch in amd64 arm64; do
          buildah manifest add "${ci_image_ref}" "docker://${ci_image_ref}-${arch}"
        done
        
        digestfile="$( mktemp )"
        buildah manifest push --all --digestfile="${digestfile}" "${ci_image_ref}" "docker://${ci_image_ref}"

        if [[ "${{ env.CI_PROMOTE }}" == "true" ]]; then
          dest_image_tag="$( tag_from_gh_ref "${GITHUB_REF}" )"
          timestamp="$( date '+%Y-%m-%d-%H%M%S' )"

          skopeo copy --all --digestfile="${digestfile}" "docker://${ci_image_ref}" "docker://${ci_repo_ref}-${dest_image_tag}-${timestamp}"
          echo '' | cat "${digestfile}" -
        
          skopeo copy --all --digestfile="${digestfile}" "docker://${ci_image_ref}" "docker://quay.io/tnozicka/ktool:${dest_image_tag}"
          echo '' | cat "${digestfile}" -
        fi

  # Wait for gating jobs so other steps have a unified step to wait on.
  gating-tests:
    name: Wait for gating tests
    runs-on: ubuntu-24.04
    needs:
    - verify
    - build
    - test-unit
    - image-build
    - image-manifest
    if: ${{ always() }}
    steps:
    - name: Fail if any gating dependency failed
      if: ${{ contains(needs.*.result, 'failure') }}
      run: exit 1

  notify-on-failure:
    name: Notify on failure
    runs-on: ubuntu-24.04
    needs:
    - gating-tests
    timeout-minutes: 15
    if: ${{ failure() && github.event_name != 'pull_request' }}
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Report failures to Slack
      if: ${{ always() }}
      uses: ./.github/actions/notify-failure
      with:
        slack-url: '${{ secrets.SLACK_WEBHOOK_URL }}'
